source "https://rails-assets.org"

gem "rails-assets-scut"
gem "rails-assets-normalize-css"
gem "rails-assets-json3"
gem "rails-assets-marionette"
gem "rails-assets-handlebars"
gem "rails-assets-fastclick"
gem "rails-assets-es6-promise"
gem "rails-assets-detectizr"