language: ruby
rvm:
  - 2.0.0-p247
before_install: brew update
install:
 - brew install advancecomp gifsicle jhead jpegoptim jpeg optipng pngcrush
 - bundle install
before_script:
  - npm install -g bower
  - bower install
script: middleman build

# whitelist
branches:
  only:
    - master
    - develop