language: ruby
rvm:
- 2.0.0-p247
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq advancecomp gifsicle jhead jpegoptim libjpeg-progs optipng
  pngcrush
- wget http://static.jonof.id.au/dl/kenutils/pngout-20130221-linux.tar.gz
- tar -xzf pngout-*-linux.tar.gz
- mv pngout-*-linux pngout-linux
env:
  matrix:
  - PATH=pngout-linux/x86_64:$PATH
  global:
  - secure: UumwD5k398TJvu9GpWPLayWTjfmeHeZ75HCxJ+RC6dPcilDQutQyEAH7IhbsQ+3jMxUIW08x9Sc8ViT6oTSjepBj88k68lqdJLQPnsTbefzfUN/cAlaDtFB3TWbenMJZJn+j+JB3PnodArVVcAL2BewzNIyWYQYJ5pGVm790JQI=
  - secure: V+YlSWFbHIi7Wi40pAwtuyOCJXcZe5BV0C4IlyQcZCVo2oh+mMMnzmNJ/Oz9zEfg0omQeDafM14y+0ahEoIaRYYeGDWG3/gw02kumQIYl77SBIQLea/VO88ZJJau3KlMU3LfTKjwzXPz0GT75aDG1Tfs9iIj1YMcwSRpNdYVcPQ=
install: bundle install
before_script:
- npm install -g bower
- bower install
script: rake mm:build:$TRAVIS_BRANCH
branches:
  only:
  - production
  - staging
