language: ruby
rvm:
- 2.0.0-p247
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq advancecomp gifsicle jhead jpegoptim libjpeg-progs optipng
  pngcrush
- wget http://static.jonof.id.au/dl/kenutils/pngout-20130221-linux.tar.gz
- tar -xzf pngout-*-linux.tar.gz
- mv pngout-*-linux pngout-linux
env:
  matrix:
  - PATH=pngout-linux/x86_64:$PATH
  global:
  - secure: lR2EWvvjPKcVQh6tASgoOp6AJTBcn+iPrFxeW+i1WcuczVCsysN8sRnQ4Ly+rGoisynDQxTawakR9uvNpxKu2xZokRnjOXxZGvVjy5hOKn8nIbdTuyf154Ys6Zjl8Cxh2O0kjaPSpN0AmbNg0NluUjVtcaI2GfsbYhzz+LPoMSk=
  - secure: hWNO5hjK/7SO34G1pRo2jF5MQQRGQNOMBQCM6PULpXwtU71p1Fl8/a1MIiUA1f6NuHwc3WnZsy+qismLpk4gaxnEotzk1nUdniZrmh3+gW378zr2kgswavxKmzePcpdm+ybMGZPePDxVf07jx7RpqecRxPW/v58AlLT+RhzRRCs=
  - secure: RsNbOg509CwpOIwYn4HQuhuJcxVIWoa4zEgR6D1O/A1soibRkZ8Nxa0Ebku/sb3VJrTbsQtdfX+XGuAnDC9INVHuFccAnXkP+pt22fb6/Ttvz336ZiYd/M0wxJj3hhHtD/NggbP6yWFhSVIhpgzFEATY0zS5eWKwTsMl+iYDv68=
  - secure: GJOPgTtKlODboVGGrxGG2gewn+WLvH9Aq96nKqo1OB6ed6FXN/4SBO5xApL46dTGFMTpZQ4t1FALlmQuw4upgv8hcdZf+LVynI5cIm+b7bFFVDOcsyUJdHU/+egN9A8wjig3wO/i9pkIIw2TAjTxB57FN0faJRKHS6u83yIgUdg=
  - secure: hNSmvqI1kjKB6T8hltxT29j23QrI14Q/sx9iHfHBg8UHoL6K2De+1eAJNEcJjcjdLNiGCrCEDHRF9lQLANZTGll7Nq26imqfnXqCR8B+mu+pnpVJXTp/DoK0igEJ7pul5JVlMUpUysJn/vjYeQeuP6W06FsRsYjM2p5odJXuJ90=
  - secure: fYXBShxlo+suXdyaL5QLSVbZwEDmeG/ScTZSBVbXXMRoLqcfE+iiM7m8w1pjDkXPXvxKyYIroBMdnbSju66ZBKrK38WJNiMCwXUZdhtvdtXjJN25X4h6/8aeKYuMWg99gfRps8EkWKgU8qg9/3OLxW6Q57ONzlkxmbKfCvDvLmg=
install:
- npm install
- npm install -g grunt-cli
- npm install -g bower
- bower install
- bundle install
script: rake mm:build:$TRAVIS_BRANCH
after_success:
- git config --global user.email "$GH_EMAIL"
- git config --global user.name "$GH_NAME"
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git config remote.origin.url https://$GH_NAME:$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git
- export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d-%H-%M-%S")-$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
- git push origin $GIT_TAG -q
- rake test:performance
branches:
  only:
  - production
  - staging
