language: ruby
rvm:
- 2.0.0-p247
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq advancecomp gifsicle jhead jpegoptim libjpeg-progs optipng
  pngcrush
- wget http://static.jonof.id.au/dl/kenutils/pngout-20130221-linux.tar.gz
- tar -xzf pngout-*-linux.tar.gz
- mv pngout-*-linux pngout-linux
env:
  matrix:
  - PATH=pngout-linux/x86_64:$PATH
  global:
  - secure: WJ7/EimVAtTAJ52e88t5x4K6ktQouWoXKtcSMFjXLd026Qu7kKf4Q5YvV3+4ZG48kslpw9cYYdEZ51C8UYnlZ2ksrDtUHhk24Z8amna+mllr8CQqaa4jgRYpT4KTxsUncf+pgU8p1XwQSIWHmeFb/tHcC3AypLy20Yo5L6o7rrk=
  - secure: G1qWMB3itXVwyPAvOPoMqQtBdbWIWoZOMhgmzrxu63r/YSLBwWMTLcHbGT0S4RCY/3rrLq3MkNSi4YE9Uu1GQittDRu4h48NhucQHoiEcRtHaUuo9sBOyMFL+rMmISIrBybMNOysCjZobJBfJaYnmlMEqw0L99rR0O6kwygRxe0=
install: bundle install
before_script:
- npm install -g bower
- bower install
script: rake mm:build:$TRAVIS_BRANCH
branches:
  only:
  - production
  - staging
