language: ruby
rvm:
- 2.0.0-p247
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq advancecomp gifsicle jhead jpegoptim libjpeg-progs optipng pngcrush
- wget http://static.jonof.id.au/dl/kenutils/pngout-20130221-linux.tar.gz
- tar -xzf pngout-*-linux.tar.gz
- mv pngout-*-linux pngout-linux
env:
  matrix:
  - PATH=pngout-linux/x86_64:$PATH
  global:
  - secure: m7ETLoFnkLv/ZMxRVRC1DaffoUcXPcmcfGnewM3SJZ/2baeNoy/pEtzIOG0oqFRAPFgeACwXgIBSHlEKbWTM9mvNnAm7B/OnpVz1rhQMIXztirW/B8aR8Y8O/sdh29kv+wZt3EjD0c0XqO9zxxWyB25qt479CoPvElqICf7aHJU=
  - secure: Nr2Rd/I9tKTslbygawQAzuf0XHHdpUqxnAGqJjldNVix2VLhant8WrteR6i4PY29nFCYLQCwBZU75ngltZpDxycDaO3nFsTQtwYpx2XaDEnjx3X/OAOuJQe6H0W3FAaJH4b0h3bwhuS/MfwFI/BypVKrBVmfa67MBodjZLDPZ70=
  - secure: aN65CeU/BNcqY4tsqC525FYTHxN3e/72Gg1GCiihew79zdz2LwT4zCHWCT9/kZ9uBO7qFNJFSN9oibtpbCcasf/WVMQhU2qTpjYRoH+bAsslKliYhUDNQCNjDPygkzQ9USiS1paS0S2dkB1p6g56M9ndGmgzQa4kgv2c4bTIZ2o=
  - secure: q2JaSlMbo+EIP9N3Y5koJbs61TPwZgii27QzkicNjdKAyKIHNLTWuFiMZWGbTZFI2xqdYMJuXFNDdNHExYgcQnvHP8B5fy2iPdROlMYwWoAOWSSBWtC2Q6+7Uz2XmLqOAzgOo2hjbtIKkDWiMn29BT4lfuAkKKcplUecQ9hUgdk=
  - secure: UTAmjm/US4Q/onc4ezMc4YiacG4v782KKgwR6KkHen4JYovKouGmR0xylz8zAEUYt+rsVEFxrHwAbqJNhAFsPumd1eegZsKPLQJLhhvJRG2hI6gmG+FjsOLgbp3bg2iXdF9TF7OaUTzIalGzjmyrJoZ4X7u0oxW0tk5TNu16kHc=
install: bundle install
before_script:
- npm install -g bower
- bower install
script: rake mm:build:$TRAVIS_BRANCH
after_success:
- git config --global user.email "$GH_EMAIL"
- git config --global user.name "$GH_NAME"
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git config remote.origin.url https://$GH_NAME:$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git
- export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d-%H-%M-%S")-$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
- git push origin $GIT_TAG
branches:
  only:
  - production
  - staging
